# Databricks notebook source
# MAGIC %md
# MAGIC # Lab of the Future Workshop - Notebook 2b
# MAGIC ## DICOM Processing with Databricks Pixels
# MAGIC 
# MAGIC This notebook demonstrates how to use the **[Databricks Pixels Solution Accelerator](https://github.com/databricks-industry-solutions/pixels)** to process and catalog DICOM medical images.
# MAGIC 
# MAGIC ### Prerequisites
# MAGIC - Run **Notebook 2a** first to generate sample DICOM data
# MAGIC - Clone the Pixels repository to your workspace
# MAGIC - DBR 14.3 LTS or later (or Serverless Compute)
# MAGIC 
# MAGIC ### What is Pixels?
# MAGIC Pixels is a Databricks Solution Accelerator for large-scale medical image processing:
# MAGIC - DICOM metadata extraction and indexing at scale
# MAGIC - SQL-accessible image catalogs stored in Delta tables
# MAGIC - PHI redaction via format-preserving encryption
# MAGIC - OHIF Viewer integration for visualization
# MAGIC - MONAI integration for AI-powered segmentation
# MAGIC 
# MAGIC ### Architecture
# MAGIC ```
# MAGIC DICOM Files (from 2a) → Pixels Catalog → Metadata Extraction → Delta Tables → SQL/ML Access
# MAGIC ```

# COMMAND ----------

# MAGIC %md
# MAGIC ## Step 1: Install Pixels Solution Accelerator
# MAGIC 
# MAGIC Pixels must be installed from the cloned GitHub repository.
# MAGIC 
# MAGIC ### Setup Instructions:
# MAGIC 1. Clone the Pixels repo into your Databricks workspace:
# MAGIC    ```
# MAGIC    Workspace > Repos > Add Repo > https://github.com/databricks-industry-solutions/pixels
# MAGIC    ```
# MAGIC 2. Adjust the path in the `%run` command below to match your clone location
# MAGIC 
# MAGIC Common paths:
# MAGIC - `/Workspace/Repos/<username>/pixels`
# MAGIC - `/Workspace/Repos/pixels`
# MAGIC - `/Workspace/Users/<email>/pixels`

# COMMAND ----------

# MAGIC %run /Workspace/Repos/pixels/config/setup

# COMMAND ----------

# MAGIC %md
# MAGIC ## Step 2: Configuration

# COMMAND ----------

# Workshop configuration - must match Notebook 2a
CATALOG = "lab_of_the_future"
SCHEMA = "healthcare_data"

# Volume path where DICOM files were saved by Notebook 2a
DICOM_VOLUME = f"/Volumes/{CATALOG}/{SCHEMA}/dicom_raw"

# Pixels catalog table (will store extracted metadata)
PIXELS_CATALOG_TABLE = f"{CATALOG}.{SCHEMA}.dicom_pixels_catalog"

print(f"DICOM Volume: {DICOM_VOLUME}")
print(f"Pixels Catalog Table: {PIXELS_CATALOG_TABLE}")

# COMMAND ----------

# MAGIC %md
# MAGIC ## Step 3: Verify Data Exists
# MAGIC 
# MAGIC Ensure Notebook 2a has been run and DICOM files exist.

# COMMAND ----------

# Check that DICOM files exist from Notebook 2a
dicom_file_count = spark.sql(f"SELECT COUNT(*) as cnt FROM lab_of_the_future.healthcare_data.dicom_metadata").collect()[0]["cnt"]
print(f"DICOM files generated by Notebook 2a: {dicom_file_count}")

if dicom_file_count == 0:
    raise Exception("No DICOM files found. Please run Notebook 2a first to generate sample data.")

# COMMAND ----------

# MAGIC %md
# MAGIC ## Step 4: Initialize Pixels Catalog
# MAGIC 
# MAGIC Use the Pixels `Catalog` class to index and catalog DICOM files.

# COMMAND ----------

from dbx.pixels import Catalog
from dbx.pixels.dicom import DicomMetaExtractor

# Initialize the Pixels Catalog
pixels_catalog = Catalog(spark)

print("Pixels Catalog initialized successfully")

# COMMAND ----------

# MAGIC %md
# MAGIC ## Step 5: Catalog DICOM Files
# MAGIC 
# MAGIC The `catalog()` method scans the volume and creates an index of all files.

# COMMAND ----------

# Catalog all DICOM files in the volume
# This creates a DataFrame with file paths and basic information
catalog_df = pixels_catalog.catalog(DICOM_VOLUME)

print(f"Files cataloged: {catalog_df.count()}")
display(catalog_df.limit(10))

# COMMAND ----------

# MAGIC %md
# MAGIC ## Step 6: Extract DICOM Metadata
# MAGIC 
# MAGIC Use `DicomMetaExtractor` to parse each DICOM file and extract all metadata tags.

# COMMAND ----------

# Extract DICOM metadata from all cataloged files
meta_df = DicomMetaExtractor(pixels_catalog).transform(catalog_df)

print(f"Metadata extracted from {meta_df.count()} DICOM files")

# Show schema
meta_df.printSchema()

# COMMAND ----------

# MAGIC %md
# MAGIC ## Step 7: Save to Delta Table
# MAGIC 
# MAGIC Persist the extracted metadata to a Delta table for SQL access.

# COMMAND ----------

# Save the Pixels catalog to Unity Catalog
pixels_catalog.save(meta_df, path=PIXELS_CATALOG_TABLE)

print(f"Saved Pixels catalog to: {PIXELS_CATALOG_TABLE}")

# COMMAND ----------

# MAGIC %md
# MAGIC ## Step 8: Query DICOM Metadata with SQL
# MAGIC 
# MAGIC Once saved, use SQL to analyze your medical imaging data.

# COMMAND ----------

# MAGIC %sql
# MAGIC -- View extracted DICOM metadata
# MAGIC SELECT 
# MAGIC   path,
# MAGIC   meta:PatientID::STRING as patient_id,
# MAGIC   meta:PatientName::STRING as patient_name,
# MAGIC   meta:Modality::STRING as modality,
# MAGIC   meta:StudyDescription::STRING as study_description,
# MAGIC   meta:SeriesDescription::STRING as series_description,
# MAGIC   meta:Manufacturer::STRING as manufacturer,
# MAGIC   meta:StudyDate::STRING as study_date,
# MAGIC   meta:Rows::INT as rows,
# MAGIC   meta:Columns::INT as columns
# MAGIC FROM lab_of_the_future.healthcare_data.dicom_pixels_catalog
# MAGIC LIMIT 20;

# COMMAND ----------

# MAGIC %sql
# MAGIC -- Analyze imaging studies by modality
# MAGIC SELECT 
# MAGIC   meta:Modality::STRING as modality,
# MAGIC   COUNT(*) as instance_count,
# MAGIC   COUNT(DISTINCT meta:PatientID::STRING) as unique_patients,
# MAGIC   COUNT(DISTINCT meta:StudyInstanceUID::STRING) as unique_studies
# MAGIC FROM lab_of_the_future.healthcare_data.dicom_pixels_catalog
# MAGIC GROUP BY meta:Modality::STRING
# MAGIC ORDER BY instance_count DESC;

# COMMAND ----------

# MAGIC %sql
# MAGIC -- Equipment utilization report
# MAGIC SELECT 
# MAGIC   meta:Manufacturer::STRING as manufacturer,
# MAGIC   meta:ManufacturerModelName::STRING as model,
# MAGIC   meta:Modality::STRING as modality,
# MAGIC   COUNT(*) as image_count,
# MAGIC   COUNT(DISTINCT meta:StudyInstanceUID::STRING) as study_count
# MAGIC FROM lab_of_the_future.healthcare_data.dicom_pixels_catalog
# MAGIC GROUP BY 
# MAGIC   meta:Manufacturer::STRING, 
# MAGIC   meta:ManufacturerModelName::STRING,
# MAGIC   meta:Modality::STRING
# MAGIC ORDER BY image_count DESC;

# COMMAND ----------

# MAGIC %md
# MAGIC ## Advanced: Incremental Processing with Auto Loader
# MAGIC 
# MAGIC For production workloads, use streaming mode to process new files as they arrive.

# COMMAND ----------

# Example: Incremental/streaming processing with Auto Loader
# Uncomment to use

# checkpoint_path = f"/Volumes/{CATALOG}/{SCHEMA}/checkpoints/pixels_catalog"
# 
# # Catalog with streaming enabled
# catalog_df_streaming = pixels_catalog.catalog(
#     DICOM_VOLUME, 
#     streaming=True, 
#     streamCheckpointBasePath=checkpoint_path
# )
# 
# # Extract metadata in streaming mode
# meta_df_streaming = DicomMetaExtractor(pixels_catalog).transform(catalog_df_streaming)
# 
# # Write as a streaming Delta table
# meta_df_streaming.writeStream \
#     .format("delta") \
#     .outputMode("append") \
#     .option("checkpointLocation", f"{checkpoint_path}/meta") \
#     .toTable(PIXELS_CATALOG_TABLE)

print("Streaming example code provided (see above)")

# COMMAND ----------

# MAGIC %md
# MAGIC ## Advanced: Metadata Anonymization (PHI Protection)
# MAGIC 
# MAGIC Pixels supports format-preserving encryption for HIPAA compliance.

# COMMAND ----------

# Example: Anonymize DICOM metadata for PHI protection
# Use secure keys from Databricks Secrets in production

# from dbx.pixels.dicom import DicomMetaAnonymizerExtractor
# 
# # Get encryption keys from secrets (recommended)
# # fp_key = dbutils.secrets.get(scope="phi-encryption", key="fp-key")
# # fp_tweak = dbutils.secrets.get(scope="phi-encryption", key="fp-tweak")
# 
# # Example keys (DO NOT use in production)
# fp_key = "2B7E151628AED2A6ABF7158809CF4F3C"  # 128-bit hex key
# fp_tweak = "A1B2C3D4E5F60718"  # 64-bit tweak
# 
# anonymized_df = DicomMetaAnonymizerExtractor(
#     pixels_catalog,
#     anonym_mode="METADATA",
#     fp_key=fp_key,
#     fp_tweak=fp_tweak,
#     anonymization_base_path=f"/Volumes/{CATALOG}/{SCHEMA}/dicom_processed"
# ).transform(catalog_df)
# 
# pixels_catalog.save(anonymized_df, path=f"{CATALOG}.{SCHEMA}.dicom_anonymized_catalog")

print("Anonymization example code provided (see above)")
print("In production, store encryption keys in Databricks Secrets")

# COMMAND ----------

# MAGIC %md
# MAGIC ## Create ML Feature View
# MAGIC 
# MAGIC Create a view optimized for machine learning pipelines.

# COMMAND ----------

# MAGIC %sql
# MAGIC -- Create a feature view for ML models
# MAGIC CREATE OR REPLACE VIEW lab_of_the_future.healthcare_data.dicom_ml_features AS
# MAGIC SELECT 
# MAGIC   path,
# MAGIC   meta:PatientID::STRING as patient_id,
# MAGIC   meta:StudyInstanceUID::STRING as study_uid,
# MAGIC   meta:SeriesInstanceUID::STRING as series_uid,
# MAGIC   meta:SOPInstanceUID::STRING as sop_uid,
# MAGIC   meta:Modality::STRING as modality,
# MAGIC   meta:StudyDescription::STRING as study_description,
# MAGIC   meta:BodyPartExamined::STRING as body_part,
# MAGIC   meta:Rows::INT as image_rows,
# MAGIC   meta:Columns::INT as image_cols,
# MAGIC   meta:BitsAllocated::INT as bits_allocated,
# MAGIC   meta:PixelSpacing::STRING as pixel_spacing,
# MAGIC   meta:SliceThickness::DOUBLE as slice_thickness,
# MAGIC   meta:Manufacturer::STRING as manufacturer,
# MAGIC   meta:InstitutionName::STRING as institution,
# MAGIC   -- Derived features
# MAGIC   meta:Rows::INT * meta:Columns::INT as total_pixels,
# MAGIC   CASE 
# MAGIC     WHEN meta:Modality::STRING IN ('CT', 'MR') THEN 'volumetric'
# MAGIC     ELSE 'planar'
# MAGIC   END as image_type,
# MAGIC   current_timestamp() as feature_extraction_time
# MAGIC FROM lab_of_the_future.healthcare_data.dicom_pixels_catalog;

# COMMAND ----------

# MAGIC %sql
# MAGIC -- Preview ML features
# MAGIC SELECT * FROM lab_of_the_future.healthcare_data.dicom_ml_features LIMIT 10;

# COMMAND ----------

# MAGIC %md
# MAGIC ## OHIF Viewer Integration
# MAGIC 
# MAGIC Pixels includes a pre-built OHIF Viewer for visualizing DICOM images directly in Databricks.
# MAGIC 
# MAGIC ### To use the OHIF Viewer:
# MAGIC 1. Navigate to the Pixels repository in your workspace
# MAGIC 2. Open and run the `06-OHIF-Viewer` notebook
# MAGIC 3. Configure:
# MAGIC    - `table`: `lab_of_the_future.healthcare_data.dicom_pixels_catalog`
# MAGIC    - `sqlWarehouseID`: Your SQL Warehouse ID (from Connection Details > HTTP path)
# MAGIC 
# MAGIC ### Features:
# MAGIC - Interactive study list from your catalog
# MAGIC - Multi-layer visualization for CT/MRI stacks
# MAGIC - Measurement and annotation tools
# MAGIC - Save segmentations back to Unity Catalog
# MAGIC 
# MAGIC ### MONAI Integration:
# MAGIC - AI-powered auto-segmentation
# MAGIC - Run the `05-MONAILabel` notebook to enable
# MAGIC - Supports custom model training

# COMMAND ----------

# MAGIC %md
# MAGIC ## Summary Statistics

# COMMAND ----------

# MAGIC %sql
# MAGIC -- Summary of DICOM data processed by Pixels
# MAGIC SELECT 
# MAGIC   'Total DICOM Files' as metric,
# MAGIC   CAST(COUNT(*) AS STRING) as value
# MAGIC FROM lab_of_the_future.healthcare_data.dicom_pixels_catalog
# MAGIC UNION ALL
# MAGIC SELECT 
# MAGIC   'Unique Patients',
# MAGIC   CAST(COUNT(DISTINCT meta:PatientID::STRING) AS STRING)
# MAGIC FROM lab_of_the_future.healthcare_data.dicom_pixels_catalog
# MAGIC UNION ALL
# MAGIC SELECT 
# MAGIC   'Unique Studies',
# MAGIC   CAST(COUNT(DISTINCT meta:StudyInstanceUID::STRING) AS STRING)
# MAGIC FROM lab_of_the_future.healthcare_data.dicom_pixels_catalog
# MAGIC UNION ALL
# MAGIC SELECT 
# MAGIC   'Unique Series',
# MAGIC   CAST(COUNT(DISTINCT meta:SeriesInstanceUID::STRING) AS STRING)
# MAGIC FROM lab_of_the_future.healthcare_data.dicom_pixels_catalog
# MAGIC UNION ALL
# MAGIC SELECT 
# MAGIC   'Modalities',
# MAGIC   CAST(COUNT(DISTINCT meta:Modality::STRING) AS STRING)
# MAGIC FROM lab_of_the_future.healthcare_data.dicom_pixels_catalog;

# COMMAND ----------

# MAGIC %md
# MAGIC ## Next Steps
# MAGIC 
# MAGIC Continue to **Notebook 3** to:
# MAGIC - Build a surgery room digital twin prototype
# MAGIC - Combine EKG data from Notebook 1 with DICOM images
# MAGIC - Integrate real-time video data from operating rooms
# MAGIC 
# MAGIC ### Resources
# MAGIC - [Pixels GitHub Repository](https://github.com/databricks-industry-solutions/pixels)
# MAGIC - [OHIF Viewer Documentation](https://docs.ohif.org/)
# MAGIC - [MONAI Medical AI Framework](https://monai.io/)
