import React, { useState } from 'react';
import { 
  AppLayout, 
  Card, 
  DataTable, 
  LineChart,
  BarChart,
  Badge,
  Tabs,
  Tab,
  Select,
  Option
} from '@databricks/appkit-ui/react';
import { useAnalyticsQuery } from '@databricks/appkit/react';

// Type definitions from appKitTypes.d.ts (generated by npm run typegen)
import type { 
  PatientSummaryRow, 
  RoomStatusRow, 
  ActiveAlertsRow,
  PatientVitalsHistoryRow,
  OperationalMetricsRow
} from './appKitTypes';

function App() {
  const [selectedPatient, setSelectedPatient] = useState<string | null>(null);
  const [activeTab, setActiveTab] = useState('overview');

  // Fetch data using generated query keys
  const { data: patients, isLoading: patientsLoading } = 
    useAnalyticsQuery<PatientSummaryRow[]>({ queryKey: 'patientSummary' });
  
  const { data: roomStatus, isLoading: roomsLoading } = 
    useAnalyticsQuery<RoomStatusRow[]>({ queryKey: 'roomStatus' });
  
  const { data: alerts, isLoading: alertsLoading } = 
    useAnalyticsQuery<ActiveAlertsRow[]>({ queryKey: 'activeAlerts' });
  
  const { data: metrics, isLoading: metricsLoading } = 
    useAnalyticsQuery<OperationalMetricsRow[]>({ queryKey: 'operationalMetrics' });

  const { data: vitalsHistory } = useAnalyticsQuery<PatientVitalsHistoryRow[]>({
    queryKey: 'patientVitalsHistory',
    params: { patient_id: selectedPatient },
    enabled: !!selectedPatient
  });

  // Calculate KPIs
  const activeRooms = roomStatus?.filter(r => r.current_status === 'in_progress').length || 0;
  const criticalAlerts = alerts?.filter(a => a.severity === 'CRITICAL' && a.alert_status === 'active').length || 0;
  const todaySurgeries = metrics?.[0]?.total_surgeries || 0;

  const getSeverityColor = (severity: string) => {
    switch (severity) {
      case 'CRITICAL': return 'red';
      case 'WARNING': return 'yellow';
      default: return 'blue';
    }
  };

  const getStatusColor = (status: string) => {
    switch (status) {
      case 'in_progress': return 'green';
      case 'critical': return 'red';
      case 'warning': return 'yellow';
      default: return 'gray';
    }
  };

  return (
    <AppLayout title="Lab of the Future" subtitle="Healthcare Digital Twin Dashboard">
      {/* KPI Cards */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: '16px', marginBottom: '24px' }}>
        <Card>
          <h3>Active Surgeries</h3>
          <p style={{ fontSize: '2rem', fontWeight: 'bold' }}>{activeRooms}</p>
        </Card>
        <Card>
          <h3>Critical Alerts</h3>
          <p style={{ fontSize: '2rem', fontWeight: 'bold', color: criticalAlerts > 0 ? 'red' : 'green' }}>
            {criticalAlerts}
          </p>
        </Card>
        <Card>
          <h3>Today's Surgeries</h3>
          <p style={{ fontSize: '2rem', fontWeight: 'bold' }}>{todaySurgeries}</p>
        </Card>
        <Card>
          <h3>Total Patients</h3>
          <p style={{ fontSize: '2rem', fontWeight: 'bold' }}>{patients?.length || 0}</p>
        </Card>
      </div>

      {/* Main Content Tabs */}
      <Tabs value={activeTab} onChange={setActiveTab}>
        <Tab value="overview" label="Room Overview" />
        <Tab value="patients" label="Patients" />
        <Tab value="alerts" label="Alerts" />
        <Tab value="analytics" label="Analytics" />
      </Tabs>

      {activeTab === 'overview' && (
        <Card title="Surgery Room Status">
          <DataTable
            data={roomStatus || []}
            loading={roomsLoading}
            columns={[
              { key: 'room_name', header: 'Room' },
              { 
                key: 'current_status', 
                header: 'Status',
                render: (row) => (
                  <Badge color={getStatusColor(row.current_status)}>
                    {row.current_status}
                  </Badge>
                )
              },
              { key: 'patient_id', header: 'Patient' },
              { key: 'procedure_type', header: 'Procedure' },
              { key: 'lead_surgeon', header: 'Surgeon' },
              { 
                key: 'patient_heart_rate', 
                header: 'Heart Rate',
                render: (row) => row.patient_heart_rate ? `${row.patient_heart_rate} BPM` : '-'
              },
              { 
                key: 'patient_status', 
                header: 'Vitals',
                render: (row) => row.patient_status ? (
                  <Badge color={getStatusColor(row.patient_status)}>
                    {row.patient_status}
                  </Badge>
                ) : '-'
              },
              { key: 'personnel_count', header: 'Staff' },
              { key: 'active_alert_count', header: 'Alerts' }
            ]}
          />
        </Card>
      )}

      {activeTab === 'patients' && (
        <>
          <Card title="Patient Selection">
            <Select 
              value={selectedPatient || ''} 
              onChange={(e) => setSelectedPatient(e.target.value)}
              placeholder="Select a patient..."
            >
              {patients?.map(p => (
                <Option key={p.patient_id} value={p.patient_id}>
                  {p.patient_id} - {p.ekg_recordings} EKGs, {p.imaging_studies} Images
                </Option>
              ))}
            </Select>
          </Card>
          
          {selectedPatient && vitalsHistory && (
            <Card title={`Heart Rate History - ${selectedPatient}`}>
              <LineChart
                data={vitalsHistory}
                xKey="recording_datetime"
                yKeys={['heart_rate_bpm']}
                height={300}
              />
            </Card>
          )}
          
          <Card title="Patient Summary">
            <DataTable
              data={patients || []}
              loading={patientsLoading}
              columns={[
                { key: 'patient_id', header: 'Patient ID' },
                { key: 'ekg_recordings', header: 'EKG Recordings' },
                { key: 'avg_heart_rate', header: 'Avg Heart Rate' },
                { key: 'min_heart_rate', header: 'Min HR' },
                { key: 'max_heart_rate', header: 'Max HR' },
                { key: 'imaging_studies', header: 'Imaging Studies' },
                { key: 'surgeries', header: 'Surgeries' }
              ]}
              onRowClick={(row) => setSelectedPatient(row.patient_id)}
            />
          </Card>
        </>
      )}

      {activeTab === 'alerts' && (
        <Card title="Alert Dashboard">
          <DataTable
            data={alerts || []}
            loading={alertsLoading}
            columns={[
              { 
                key: 'severity', 
                header: 'Severity',
                render: (row) => (
                  <Badge color={getSeverityColor(row.severity)}>
                    {row.severity}
                  </Badge>
                )
              },
              { key: 'room_name', header: 'Room' },
              { key: 'patient_id', header: 'Patient' },
              { key: 'message', header: 'Message' },
              { 
                key: 'alert_status', 
                header: 'Status',
                render: (row) => (
                  <Badge color={row.alert_status === 'active' ? 'red' : 'gray'}>
                    {row.alert_status}
                  </Badge>
                )
              },
              { key: 'triggered_at', header: 'Triggered' },
              { key: 'duration_minutes', header: 'Duration (min)' }
            ]}
          />
        </Card>
      )}

      {activeTab === 'analytics' && (
        <>
          <Card title="Daily Surgery Volume (Last 30 Days)">
            <BarChart
              data={metrics || []}
              xKey="date"
              yKeys={['total_surgeries', 'completed', 'cancelled']}
              height={300}
            />
          </Card>
          <Card title="Operational Metrics">
            <DataTable
              data={metrics || []}
              loading={metricsLoading}
              columns={[
                { key: 'date', header: 'Date' },
                { key: 'total_surgeries', header: 'Total Surgeries' },
                { key: 'unique_patients', header: 'Patients' },
                { key: 'rooms_used', header: 'Rooms Used' },
                { key: 'avg_duration_minutes', header: 'Avg Duration (min)' },
                { key: 'completed', header: 'Completed' },
                { key: 'cancelled', header: 'Cancelled' }
              ]}
            />
          </Card>
        </>
      )}
    </AppLayout>
  );
}

export default App;
